### ISSUE TITLE
hourglass model cannot compile

### ISSUE THREAD

**Issue by daskandalis** [talmolab/sleap#1607] opened 2023-11-25 14:30 UTC
# Bug description
Hourglass model preset fails to compile.

## Expected behaviour
Model runs.

## Actual behaviour
Terminates with: ValueError: The name "SingleInstanceConfmapsHead" is used 3 times in the model. All layer names should be unique.

## Your personal set up
- OS:
Windows 11

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [X] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

**Comment by roomrys** [comment] 2023-11-27 17:28
Thanks for reporting! This is a duplicate of #715, we will follow the discussion there.

**Closed by roomrys** 2023-11-27 17:28 UTC
Labels: bug
