### ISSUE TITLE
 error while opening GUI: "argument 1 has unexpected type 'QRect'"

### ISSUE THREAD

**Issue by MirjamH** [talmolab/sleap#984] opened 2022-10-06 11:03 UTC
Hi, 
I got the following error when trying the "sleap-label" command:  

File "C:\Users\Admin\anaconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\slider.py", line 408, in box_rect
    self.setSceneRect(rect)
TypeError: arguments did not match any overloaded call:
  setSceneRect(self, QRectF): argument 1 has unexpected type 'QRect'
  setSceneRect(self, float, float, float, float): argument 1 has unexpected type 'QRect'

I managed to solve it by changing all the QRect into QRectF, so I am guessing it is a typo in the slyder.py file? Just to let you know, maybe I didn't quite solve it, but like this the GUI at least opened. 

---

## Your personal set up

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

**Comment by roomrys** [comment] 2022-10-06 16:27
Hi @MirjamH,

Thanks for reporting! I edited your response - do you mind telling us a bit about your set-up (version of SLEAP and running 'conda list' in your terminal)? 

This seems like a set-up specific discrepancy (and may have been caused by adding a Qt interpreter in our latest release).

Thanks, 
Liezl

**Comment by MirjamH** [comment] 2022-10-11 12:39
Hi! I am sorry for not responding sooner, but I will delete my message
again, because it must have been something with my computer. Two colleagues
installed it the exact same way and did not have any errors. I suspect it
was a problem with my anaconda installation (which was done a while ago).
Anyhow, thanks a lot for responding, if I run into more problems I'll let
you know for some more help :)
Cheers, Mirjam

**Comment by roomrys** [comment] 2022-10-11 17:09
Thanks for the update! @MirjamH 

Let us know if updating anaconda fixes things. Otherwise, we can help troubleshoot (given some info on your set-up).

Thanks,
Liezl

**Comment by roomrys** [comment] 2022-11-07 20:05
Hi @MirjamH,

We are closing this issue for now, but feel free to reply here if you are still experiencing issues and we will re-open it!

Thanks,
Liezl

**Closed by roomrys** 2022-11-07 20:05 UTC
Labels: waiting for user input

**Comment by lambdaloop** [comment] 2024-09-10 20:50
I came across this issue when trying to run sleap today. If anyone comes across it, the issue was that I was running with python 3.10 . When running with python=3.7.12 as recommended in the sleap docs, the issue was fixed.
