### ISSUE TITLE
Merging labels package and predictions results in mixed color/grayscale project 

### ISSUE THREAD

**Issue by Alceec** [talmolab/sleap#927] opened 2022-08-29 12:17 UTC
# Bug description

I labeled some videos and saved the labels under the name labels_1.pkg.slp. Then I trained a model on these labels (with sleap-train) and generated predictions on an unseen video (with sleap-track). I opened this new video with the predicted labels in the GUI, refined the labels in 20 frames and exported the labels to a second dataset called labels_2.pkg.slp. 
Now I want to merge both datasets labels_1.pkg.slp and labels_2.pkg.slp into one labels package. I'm using the "Merge Into Project..." option, creating my new labels package and trying to train it on my GPU via the command 'sleap-train' but I get an error.

## Expected behaviour

I should be able to use the sleap-train command on my merged dataset.

## Actual behaviour

When training, I get this error :
<img width="897" alt="merging_error" src="https://user-images.githubusercontent.com/33930767/187195149-09d6b251-f4b0-49e0-bff7-dd6e69cea1aa.png">
When I train the model on the two datasets separately without merging them together, everything works perfectly.

Also, I observe a strange behavior in the GUI. In labels_2.pkg.slp, I have 20 labeled frames and 264 predictions, but it seems like there is some confusion between the total number of frames and the number of labeled frames.
<img width="604" alt="merging_error2" src="https://user-images.githubusercontent.com/33930767/187198853-33a11cb8-4bb9-4fa8-b484-2fc46ad5fc38.PNG">

## Your personal set up

- OS: ubuntu 20.04.4

- Version(s): SLEAP 1.2.3, python 3.7.12

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)): Conda from package(https://sleap.ai/installation.html#conda-package)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
INFO:sleap.nn.training:Creating tf.data.Datasets for training data generation...
Traceback (most recent call last):
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\Scripts\sleap-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap', 'console_scripts', 'sleap-train')())
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\training.py", line 1969, in main
    trainer.train()
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\training.py", line 914, in train
    training_ds = self.training_pipeline.make_dataset()
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\data\pipelines.py", line 287, in make_dataset
    ds = transformer.transform_dataset(ds)
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\data\dataset_ops.py", line 318, in transform_dataset
    self.examples = list(iter(ds))
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 836, in __next__
    return self._next_internal()
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 822, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2922, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\framework\ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape of tensor EagerPyFunc [159,1968,1] is not compatible with expected shape [?,?,3].
         [[{{node EnsureShape}}]] [Op:IteratorGetNext]
2022-09-09 14:31:15.637339: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

</details>

## How to reproduce

1. Open labels_1.pkg.slp
2. Go on 'File'
3. Click on 'Merge Into Project...'
4. Select labels_2.pkg.slp
5. Train on the GPU with the command line 'sleap-train'

**Comment by talmo** [comment] 2022-09-07 23:57
Following up from the email:

As a workaround for now, can you try merging the original SLP files rather than exporting them as packages first and let us know if it works?

This might break some paths, but you can fix those by opening it in the GUI and re-locating the videos, or by going to File -> Replace Videos...

**Comment by roomrys** [comment] 2022-09-09 21:43
Hi @Alceec,

## Cause
I took a look at the dataset you provided and attempted to run training which resulted in this traceback:
```
INFO:sleap.nn.training:Creating tf.data.Datasets for training data generation...
Traceback (most recent call last):
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\Scripts\sleap-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap', 'console_scripts', 'sleap-train')())
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\training.py", line 1969, in main
    trainer.train()
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\training.py", line 914, in train
    training_ds = self.training_pipeline.make_dataset()
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\data\pipelines.py", line 287, in make_dataset
    ds = transformer.transform_dataset(ds)
  File "d:\social-leap-estimates-animal-poses\pull-requests\sleap_127_dev\sleap\sleap\nn\data\dataset_ops.py", line 318, in transform_dataset
    self.examples = list(iter(ds))
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 836, in __next__
    return self._next_internal()
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 822, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2922, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\TalmoLab\miniconda3\envs\sleap_merge\lib\site-packages\tensorflow\python\framework\ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape of tensor EagerPyFunc [159,1968,1] is not compatible with expected shape [?,?,3].
         [[{{node EnsureShape}}]] [Op:IteratorGetNext]
2022-09-09 14:31:15.637339: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

The error is being caused by having a mix of grayscale and color videos in the merged project as we see from this line in the traceback:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape of tensor EagerPyFunc [159,1968,1] is not compatible with expected shape [?,?,3].
```
 The predictions slp had a grayscale video and the training labels slp had all color videos. We currently have an issue open about this #759. 


## Workaround
The workaround is to use the "Toggle Grayscale" button on the selected video (I believe it is the first video in your dataset) and ensure all videos have the same number of channels. The number of channels for each video will be listed in the right-most column of the video dialog (View > Videos).

Let us know if you run into any trouble and/or if you need help.

Thanks,
Liezl

**Comment by Alceec** [comment] 2022-10-05 14:52
Thank you very much, it does indeed work now. Sorry for my late reply, I was on vacation.

Thank you,
Louise

**Comment by talmo** [comment] 2024-12-16 23:37
Closing as there is a workaround for now.

**Closed by talmo** 2024-12-16 23:37 UTC
Labels: bug
