### ISSUE TITLE
Error importing deeplabcut type dataset

### ISSUE THREAD

**Issue by wyclearnpy** [talmolab/sleap#1921] opened 2024-08-27 08:43 UTC
When I imported the DEEPLABCUT data set, the following error occurred. This did not happen before, and it still does not work after reinstalling.
Terminal print information：

```python
Restoring GUI state...
[ WARN:0@130.958] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img005.png'): can't open/read file: check file path/integrity
Error occurred during callback 0 for video!
[<bound method QtVideoPlayer.load_video of <sleap.gui.widgets.video.QtVideoPlayer(0x1d0413d9410) at 0x000001D041EEA0C0>>, <function MainWindow._create_video_player.<locals>.switch_frame at 0x000001D041FE7CA0>, <function MainWindow._create_video_player.<locals>.<lambda> at 0x000001D041FE7DC0>, <function MainWindow._create_video_player.<locals>.update_frame_chunk_suggestions at 0x000001D041FE7D30>]
'NoneType' object has no attribute 'shape'
[ WARN:0@130.963] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img005.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1235, in _after_plot_change
    overlay.redraw(self.state["video"], frame_idx)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\overlays\base.py", line 85, in redraw
    self.add_to_scene(video, frame_idx, *args, **kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\overlays\instance.py", line 46, in add_to_scene
    self.player.addInstance(
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 469, in addInstance
    instance = QtInstance(instance=instance, player=self, **kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 1808, in __init__
    max_x=self.player.video.width, max_y=self.player.video.height
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 1046, in __getattr__
    return getattr(self.backend, item)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 922, in width
    self._load_test_frame()
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 861, in _load_test_frame
    test_frame_ = self._load_idx(0)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 840, in _load_idx
    if img.shape[2] == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:1@130.971] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img290.png'): can't open/read file: check file path/integrity
[ WARN:0@130.972] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img005.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1235, in _after_plot_change
    overlay.redraw(self.state["video"], frame_idx)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\overlays\base.py", line 85, in redraw
    self.add_to_scene(video, frame_idx, *args, **kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\overlays\instance.py", line 46, in add_to_scene
    self.player.addInstance(
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 469, in addInstance
    instance = QtInstance(instance=instance, player=self, **kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 1808, in __init__
    max_x=self.player.video.width, max_y=self.player.video.height
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 1046, in __getattr__
    return getattr(self.backend, item)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 922, in width
    self._load_test_frame()
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 861, in _load_test_frame
    test_frame_ = self._load_idx(0)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 840, in _load_idx
    if img.shape[2] == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:0@130.982] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img005.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 309, in importDLC
    self.execute(ImportDeepLabCut)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 242, in execute
    command().execute(context=self, params=kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 138, in execute
    self.do_with_signal(context, params)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 162, in do_with_signal
    cls.do_action(context, params)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 944, in do_action
    new_window.commands.loadLabelsObject(labels=labels)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 261, in loadLabelsObject
    self.execute(LoadLabelsObject, labels=labels, filename=filename)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 242, in execute
    command().execute(context=self, params=kwargs)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 138, in execute
    self.do_with_signal(context, params)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 162, in do_with_signal
    cls.do_action(context, params)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 675, in do_action
    context.app.on_data_update([UpdateTopic.project, UpdateTopic.all])
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1166, in on_data_update
    self.videos_dock.table.model().items = self.labels.videos
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 103, in items
    item_data = self.item_to_data(obj, item)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 392, in item_to_data
    return {key: getattr(item, key) for key in self.properties}
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 392, in <dictcomp>
    return {key: getattr(item, key) for key in self.properties}
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 1046, in __getattr__
    return getattr(self.backend, item)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 934, in height
    self._load_test_frame()
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 861, in _load_test_frame
    test_frame_ = self._load_idx(0)
  File "D:\anaconda\envs\sleap\lib\site-packages\sleap\io\video.py", line 840, in _load_idx
    if img.shape[2] == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:1@131.001] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img290.png'): can't open/read file: check file path/integrity
```

**Comment by ahmar7** [comment] 2024-08-27 08:43
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment] 2024-08-27 08:43
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment] 2024-08-27 08:44
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment] 2024-08-27 08:44
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment] 2024-08-27 08:44
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment] 2024-08-27 08:46
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment] 2024-08-27 08:46
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wyclearnpy** [comment] 2024-08-27 09:02
Okay, the file has been downloaded. How do I install it? Should I choose the win64.exe file? But my computer is not responding. How do I choose another path?Is there a detailed installation process?

**Comment by eberrigan** [comment] 2024-08-27 16:26
The issue is the location of your images:
```
[ WARN:0@130.958] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/wyc/Desktop/鏉愭枡/dlc_own/2cam_fish-wyc-2024-04-18/labeled-data/1_camA\img005.png'): can't open/read file: check file path/integrity
```
You have non ASCII characters in your filepath. You should rename "鏉愭枡" to something with ASCII characters to prevent issues across various software. 

Then you can try reading your image path with something like 
```
img = cv2.imread('<path/to/image/with/ASCII/characters/only')
```

Sorry I am a bit confused about your second question. What are you trying to install?

**Comment by wyclearnpy** [comment] 2024-08-28 01:26
The second problem is that I received a reply before that I needed to download a repair tool, but it seems to have been deleted now. Thanks for your reply, I think I know what's wrong.

**Comment by eberrigan** [comment] 2024-08-28 02:31
Hi @wyclearnpy,

I can see the deleted thread in my email. You should not have to install anything besides our recommended installation methods for SLEAP, which does not include a windows installer. Please do not click on the link that was shared. It was not from our team and it was likely deleted from GitHub because it is a phishing scam. 

If you have clicked the link, you should delete the downloaded file, backup your important files and wipe your computer. You should also change your passwords. Sorry for the inconvenience.

Best of luck,

Elizabeth

**Comment by roomrys** [comment] 2024-08-28 16:55
Testing whether a deleted comment shows up in the chat history

**Comment by roomrys** [comment] 2024-08-29 18:11
Yes, these attacks seem to be common, so we should definitely warn our users to be careful and/or consider implementing a bot that auto-responds to new issues/discussions with a warning to take everything with scrutiny - even more so if the poster is not a Maintainer/Moderator.
[Github is flooded with social engineering attacks and nothing can be done about it? #136836](https://github.com/orgs/community/discussions/136836)

**Comment by roomrys** [comment] 2024-08-31 16:18
Closing this issues as completed since the user has stated
> Thanks for your reply, I think I know what's wrong.

but, if this is still a problem, feel free to comment below and we will reopen the issue.

Thanks,
Liezl

**Closed by roomrys** 2024-08-31 16:18 UTC
Labels: bug
