### ISSUE TITLE
Dependency range too broad for linux installation

### ISSUE THREAD

**Issue by boergens** [talmolab/sleap#1428] opened 2023-07-28 23:10 UTC
Trying to run sleap-label

following these instructions:
https://github.com/talmolab/sleap/releases

```mamba create -y -n sleap -c conda-forge -c nvidia -c sleap -c anaconda sleap=1.3.1```

activatint sleap environment

gives the error message from the title

All on Ubuntu 22.04 LTS, fresh user

```
The 'setuptools' distribution was not found and is required by pynwb
```

**Comment by roomrys** [comment] 2023-08-10 17:16
Hi @boergens,

I created and uploaded a new build for sleap 1.3.1 linux-64. To make sure you are pulling in the new build instead a cached one, do you mind trying the command:

```bash
mamba create -y -n sleap_test_0 -c conda-forge -c nvidia -c sleap -c anaconda sleap=1.3.1=py37_11
```

Then run

```bash
mamba activate sleap_test_0
```

and finally

```bash
sleap-label
```

If it the `sleap_test_0` environment works for you, then I will go ahead and close this issue.

Thanks,
Liezl

**Comment by roomrys** [comment] 2023-08-24 18:46
We received another post about this issue in #1467:

---

Thank you for developing this wonderful software.

We installed SLEAP on Linux (Ubuntu 20.04.5 LTS) via following command
`mamba create -y -n sleap -c conda-forge -c nvidia -c sleap -c anaconda sleap=1.3.1`

Installation was completed successfully.
However, sleap-label and sleap-diagnostic command (after "conda activate sleap")
give following errors

`pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by pynwb`

We confirmed the installation. But, 
'mamba install setuptools 
mamba install pynwb'
showed that the packages have been installed. 

This may be a problem on the pynwb side, but if there is any solution, please let me know.

_Originally posted by @maedat in https://github.com/talmolab/sleap/discussions/1467_

**Comment by roomrys** [comment] 2023-08-24 18:49
Hi @maedat,

__Before you try reinstalling__, can you activate the broken SLEAP installation and run the commands
```bash
mamba list
pip freeze
```
and post the output for both.

__Is this a new installation or are you upgrading your version of SLEAP?__ I would expect that a completely new installation (never before installed SLEAP... or any other packages using conda) would not have this problem and would be a bit more concerned if it is the former.

Also let us know if the package/[command above](https://github.com/talmolab/sleap/issues/1428#issuecomment-1673606364) works for you!

Thanks,
Liezl

**Comment by eringiglio** [comment] 2023-09-01 21:00
Ah, awesome--ran into this myself today... after deleting my entire SLEAP conda env and then installing a new version. I can't remember what errors I was running into that made that necessary, but it looks to me like it miiiiight have been the upgrade? 

I am getting the same setuptools error despite having the setuptools package installed. I am running this installation on a headless Linux cluster. 

I have now tried running "mamba activate sleap" as well as "conda activate sleap"--same error. I have also tried running both conda and "mamba update sleap" -- no improvement. 

Here are my results from "mamba list":

> # packages in environment at /panfs/jay/groups/24/ngrissom/gigli029/mambaforge/envs/sleap:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       2_gnu    conda-forge
> absl-py                   1.0.0                    pypi_0    pypi
> alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
> astunparse                1.6.3                    pypi_0    pypi
> attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
> backports-zoneinfo        0.2.1                    pypi_0    pypi
> bottleneck                1.3.5            py37hda87dfa_0    conda-forge
> brotli                    1.0.9                h166bdaf_9    conda-forge
> brotli-bin                1.0.9                h166bdaf_9    conda-forge
> bzip2                     1.0.8                h7f98852_4    conda-forge
> c-ares                    1.19.1               hd590300_0    conda-forge
> ca-certificates           2023.7.22            hbcca054_0    conda-forge
> cached-property           1.5.2                hd8ed1ab_1    conda-forge
> cached_property           1.5.2              pyha770c72_1    conda-forge
> cachetools                4.2.4                    pypi_0    pypi
> cairo                     1.16.0            h6cf1ce9_1008    conda-forge
> cattrs                    1.1.1              pyhd8ed1ab_0    conda-forge
> certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
> charset-normalizer        2.0.9                    pypi_0    pypi
> cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
> cuda-nvcc                 11.3.58              h2467b9f_0    nvidia
> cudatoolkit               11.3.1              hb98b00a_12    conda-forge
> cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
> cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
> cytoolz                   0.12.0           py37h540881e_0    conda-forge
> dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
> dbus                      1.13.6               h5008d03_3    conda-forge
> efficientnet              1.0.0                    pypi_0    pypi
> expat                     2.5.0                hcb278e6_1    conda-forge
> ffmpeg                    4.3.2                h37c90e5_3    conda-forge
> flatbuffers               2.0                      pypi_0    pypi
> fontconfig                2.14.2               h14ed4e7_0    conda-forge
> fonttools                 4.38.0           py37h540881e_0    conda-forge
> freetype                  2.12.1               hca18f0e_1    conda-forge
> fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
> gast                      0.4.0                    pypi_0    pypi
> geos                      3.11.0               h27087fc_0    conda-forge
> gettext                   0.21.1               h27087fc_0    conda-forge
> gmp                       6.2.1                h58526e2_0    conda-forge
> gnutls                    3.6.13               h85f3911_1    conda-forge
> google-auth               2.3.3                    pypi_0    pypi
> google-auth-oauthlib      0.4.6                    pypi_0    pypi
> google-pasta              0.2.0                    pypi_0    pypi
> graphite2                 1.3.13            h58526e2_1001    conda-forge
> grpcio                    1.43.0                   pypi_0    pypi
> gst-plugins-base          1.18.5               hf529b03_3    conda-forge
> gstreamer                 1.18.5               h9f60fe5_3    conda-forge
> h5py                      3.1.0           nompi_py37h1e651dc_100    conda-forge
> harfbuzz                  2.9.1                h83ec7ef_1    conda-forge
> hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
> icu                       68.2                 h9c3ff4c_0    conda-forge
> idna                      3.3                      pypi_0    pypi
> image-classifiers         1.0.0                    pypi_0    pypi
> imagecodecs-lite          2019.12.3        py37hc105733_5    conda-forge
> imageio                   2.31.1             pyh24c5eb1_0    conda-forge
> imgaug                    0.4.0              pyhd8ed1ab_1    conda-forge
> imgstore                  0.2.9                    pypi_0    pypi
> importlib-metadata        4.10.0                   pypi_0    pypi
> importlib-resources       5.12.0                   pypi_0    pypi
> jasper                    1.900.1           h07fcdf6_1006    conda-forge
> joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
> jpeg                      9e                   h0b41bf4_3    conda-forge
> jsmin                     3.0.1              pyhd8ed1ab_0    conda-forge
> jsonpickle                1.2                        py_0    conda-forge
> jsonschema                4.17.3                   pypi_0    pypi
> keras                     2.7.0                    pypi_0    pypi
> keras-applications        1.0.8                    pypi_0    pypi
> keras-preprocessing       1.1.2                    pypi_0    pypi
> keyutils                  1.6.1                h166bdaf_0    conda-forge
> kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
> krb5                      1.19.3               h3790be6_0    conda-forge
> lame                      3.100             h166bdaf_1003    conda-forge
> lcms2                     2.14                 h6ed2654_0    conda-forge
> ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
> lerc                      4.0.0                h27087fc_0    conda-forge
> libblas                   3.9.0           17_linux64_openblas    conda-forge
> libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
> libbrotlidec              1.0.9                h166bdaf_9    conda-forge
> libbrotlienc              1.0.9                h166bdaf_9    conda-forge
> libcblas                  3.9.0           17_linux64_openblas    conda-forge
> libclang                  12.0.0                   pypi_0    pypi
> libcurl                   7.86.0               h7bff187_1    conda-forge
> libdeflate                1.14                 h166bdaf_0    conda-forge
> libedit                   3.1.20191231         he28a2e2_2    conda-forge
> libev                     4.33                 h516909a_1    conda-forge
> libevent                  2.1.10               h9b69904_4    conda-forge
> libexpat                  2.5.0                hcb278e6_1    conda-forge
> libffi                    3.4.2                h7f98852_5    conda-forge
> libgcc-ng                 13.1.0               he5830b7_0    conda-forge
> libgfortran-ng            13.1.0               h69a702a_0    conda-forge
> libgfortran5              13.1.0               h15d22d2_0    conda-forge
> libglib                   2.76.4               hebfc3b9_0    conda-forge
> libgomp                   13.1.0               he5830b7_0    conda-forge
> libiconv                  1.17                 h166bdaf_0    conda-forge
> liblapack                 3.9.0           17_linux64_openblas    conda-forge
> liblapacke                3.9.0           17_linux64_openblas    conda-forge
> libllvm11                 11.1.0               he0ac6c6_5    conda-forge
> libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
> libnsl                    2.0.0                h7f98852_0    conda-forge
> libogg                    1.3.4                h7f98852_1    conda-forge
> libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
> libopencv                 4.5.3            py37h25009ff_1    conda-forge
> libopus                   1.3.1                h7f98852_1    conda-forge
> libpng                    1.6.39               h753d276_0    conda-forge
> libpq                     13.8                 hd77ab85_0    conda-forge
> libprotobuf               3.16.0               h780b84a_0    conda-forge
> libsodium                 1.0.18               h36c2ea0_1    conda-forge
> libsqlite                 3.43.0               h2797004_0    conda-forge
> libssh2                   1.10.0               haa6b8db_3    conda-forge
> libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
> libtiff                   4.4.0                h82bc61c_5    conda-forge
> libuuid                   2.38.1               h0b41bf4_0    conda-forge
> libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
> libwebp-base              1.3.1                hd590300_0    conda-forge
> libxcb                    1.13              h7f98852_1004    conda-forge
> libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
> libxml2                   2.9.12               h72842e0_0    conda-forge
> libxslt                   1.1.33               h15afd5d_2    conda-forge
> libzlib                   1.2.13               hd590300_5    conda-forge
> locket                    1.0.0              pyhd8ed1ab_0    conda-forge
> markdown                  3.3.6                    pypi_0    pypi
> markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
> matplotlib-base           3.5.3            py37hf395dca_2    conda-forge
> mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
> munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
> mysql-common              8.0.32               h14678bc_0    conda-forge
> mysql-libs                8.0.32               h54cf53e_0    conda-forge
> ncurses                   6.4                  hcb278e6_0    conda-forge
> ndx-pose                  0.1.1                    pypi_0    pypi
> nettle                    3.6                  he412f7d_0    conda-forge
> networkx                  2.7                pyhd8ed1ab_0    conda-forge
> nixio                     1.5.3                    pypi_0    pypi
> nomkl                     1.0                  h5ca1d4c_0    conda-forge
> nspr                      4.35                 h27087fc_0    conda-forge
> nss                       3.92                 h1d7d5a4_0    conda-forge
> numexpr                   2.8.3           py37h85a3170_100    conda-forge
> numpy                     1.19.5                   pypi_0    pypi
> oauthlib                  3.1.1                    pypi_0    pypi
> opencv                    4.5.3            py37h89c1867_1    conda-forge
> opencv-python-headless    4.2.0.34                 pypi_0    pypi
> openh264                  2.1.1                h780b84a_0    conda-forge
> openjpeg                  2.5.0                h7d73246_1    conda-forge
> openssl                   1.1.1v               hd590300_0    conda-forge
> opt-einsum                3.3.0                    pypi_0    pypi
> packaging                 21.3                     pypi_0    pypi
> pandas                    1.3.5            py37h8c16a72_0    anaconda
> partd                     1.4.0              pyhd8ed1ab_0    conda-forge
> patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
> pcre2                     10.40                hc3806b6_0    conda-forge
> pillow                    9.2.0            py37h850a105_2    conda-forge
> pip                       23.2.1             pyhd8ed1ab_0    conda-forge
> pixman                    0.40.0               h36c2ea0_0    conda-forge
> pkgutil-resolve-name      1.3.10                   pypi_0    pypi
> protobuf                  3.19.1                   pypi_0    pypi
> psutil                    5.9.3            py37h540881e_0    conda-forge
> pthread-stubs             0.4               h36c2ea0_1001    conda-forge
> py-opencv                 4.5.3            py37h6531663_1    conda-forge
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
> pykalman                  0.9.5                      py_1    conda-forge
> pynwb                     2.3.3                    pypi_0    pypi
> pyparsing                 3.0.6                    pypi_0    pypi
> pyrsistent                0.19.3                   pypi_0    pypi
> pyside2                   5.13.2           py37hfa98aef_7    conda-forge
> python                    3.7.12          hb7a2778_100_cpython    conda-forge
> python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> python-rapidjson          1.9              py37hd23a5d3_0    conda-forge
> python_abi                3.7                     3_cp37m    conda-forge
> pytz                      2023.3             pyhd8ed1ab_0    conda-forge
> pywavelets                1.3.0            py37hda87dfa_1    conda-forge
> pyyaml                    6.0              py37h540881e_4    conda-forge
> pyzmq                     24.0.1           py37h0c0c2a8_0    conda-forge
> qimage2ndarray            1.10.0                   pypi_0    pypi
> qt                        5.12.9               hda022c4_4    conda-forge
> qtpy                      2.4.0              pyhd8ed1ab_0    conda-forge
> readline                  8.2                  h8228510_1    conda-forge
> requests                  2.26.0                   pypi_0    pypi
> requests-oauthlib         1.3.0                    pypi_0    pypi
> rich                      13.5.1             pyhd8ed1ab_0    conda-forge
> ruamel-yaml               0.17.32                  pypi_0    pypi
> ruamel-yaml-clib          0.2.7                    pypi_0    pypi
> scikit-image              0.19.2           py37he8f5f7f_0    conda-forge
> scikit-learn              1.0              py37hf0f1638_1    conda-forge
> scikit-video              1.1.11             pyh24bf2e0_0    conda-forge
> scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
> seaborn                   0.12.2               hd8ed1ab_0    conda-forge
> seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
> segmentation-models       1.0.1                    pypi_0    pypi
> setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
> setuptools-scm            6.3.2                    pypi_0    pypi
> shapely                   1.8.5            py37ha4e3bd1_0    conda-forge
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> sleap                     1.3.1                    pypi_0    pypi
> sqlite                    3.43.0               h2c6b66d_0    conda-forge
> statsmodels               0.13.2           py37hda87dfa_0    conda-forge
> tensorboard               2.7.0                    pypi_0    pypi
> tensorboard-data-server   0.6.1                    pypi_0    pypi
> tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
> tensorflow                2.7.0                    pypi_0    pypi
> tensorflow-estimator      2.7.0                    pypi_0    pypi
> tensorflow-hub            0.13.0             pyh56297ac_0    conda-forge
> tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi
> termcolor                 1.1.0                    pypi_0    pypi
> threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
> tifffile                  2020.6.3                   py_0    conda-forge
> tk                        8.6.12               h27826a3_0    conda-forge
> tomli                     2.0.0                    pypi_0    pypi
> toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
> typing-extensions         4.0.1                    pypi_0    pypi
> typing_extensions         4.7.1              pyha770c72_0    conda-forge
> tzlocal                   5.0.1                    pypi_0    pypi
> unicodedata2              14.0.0           py37h540881e_1    conda-forge
> urllib3                   1.26.7                   pypi_0    pypi
> werkzeug                  2.0.2                    pypi_0    pypi
> wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
> wrapt                     1.13.3                   pypi_0    pypi
> x264                      1!161.3030           h7f98852_1    conda-forge
> xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
> xorg-libice               1.1.1                hd590300_0    conda-forge
> xorg-libsm                1.2.4                h7391055_0    conda-forge
> xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
> xorg-libxau               1.0.11               hd590300_0    conda-forge
> xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
> xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
> xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
> xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
> xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
> xorg-xproto               7.0.31            h7f98852_1007    conda-forge
> xz                        5.2.6                h166bdaf_0    conda-forge
> yaml                      0.2.5                h7f98852_2    conda-forge
> zeromq                    4.3.4                h9c3ff4c_1    conda-forge
> zipp                      3.6.0                    pypi_0    pypi
> zlib                      1.2.13               hd590300_5    conda-forge
> zstd                      1.5.5                hfc55251_0    conda-forge

Here's what I get when I run "pip freeze":

> 
> absl-py==1.0.0
> astunparse==1.6.3
> attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1640799537051/work
> backports.zoneinfo==0.2.1
> Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1656803757560/work
> cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
> cachetools==4.2.4
> cattrs @ file:///home/conda/feedstock_root/build_artifacts/cattrs_1604136207372/work
> certifi==2023.7.22
> charset-normalizer==2.0.9
> cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
> cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
> cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1657553457169/work
> dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1644602974678/work
> efficientnet==1.0.0
> flatbuffers==2.0
> fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1666389892786/work
> fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1674184942191/work
> gast==0.4.0
> google-auth==2.3.3
> google-auth-oauthlib==0.4.6
> google-pasta==0.2.0
> grpcio==1.43.0
> h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1604753641401/work
> hdmf==3.6.1
> idna==3.3
> image-classifiers==1.0.0
> imagecodecs-lite @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs-lite_1665171202021/work
> imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1686552404404/work
> imgaug @ file:///home/conda/feedstock_root/build_artifacts/imgaug_1640909786103/work
> imgstore==0.2.9
> importlib-metadata==4.10.0
> importlib-resources==5.12.0
> joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1691577114857/work
> jsmin @ file:///home/conda/feedstock_root/build_artifacts/jsmin_1642532731678/work
> jsonpickle==1.2
> jsonschema==4.17.3
> keras==2.7.0
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.2
> kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1657953088445/work
> libclang==12.0.0
> locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
> Markdown==3.3.6
> markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1677100944732/work
> matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1661439848456/work
> mdurl @ file:///home/conda/feedstock_root/build_artifacts/mdurl_1639515908913/work
> munkres==1.1.4
> ndx-pose==0.1.1
> networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1646092782768/work
> nixio==1.5.3
> numexpr @ file:///home/conda/feedstock_root/build_artifacts/numexpr_1658076415990/work
> numpy==1.19.5
> oauthlib==3.1.1
> opencv-python-headless==4.2.0.34
> opt-einsum==3.3.0
> packaging==21.3
> pandas==1.3.5
> partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
> patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1665356157073/work
> Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1660385854171/work
> pkgutil_resolve_name==1.3.10
> protobuf==3.16.0
> psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1666155398032/work
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1691408637400/work
> pykalman==0.9.5
> pynwb==2.3.3
> pyparsing==3.0.6
> pyrsistent==0.19.3
> PySide2==5.13.2
> python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
> python-rapidjson @ file:///home/conda/feedstock_root/build_artifacts/python-rapidjson_1665999896718/work
> pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
> PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1649616401885/work
> PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1648757092905/work
> pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1663830492333/work
> qimage2ndarray==1.10.0
> QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1693347765905/work
> requests==2.26.0
> requests-oauthlib==1.3.0
> rich @ file:///home/conda/feedstock_root/build_artifacts/rich-split_1690807641695/work/dist
> rsa==4.8
> ruamel.yaml==0.17.32
> ruamel.yaml.clib==0.2.7
> scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1645196656256/work
> scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1632611341839/work
> scikit-video==1.1.11
> scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1637806658031/work
> seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1672497695270/work
> segmentation-models==1.0.1
> setuptools-scm==6.3.2
> Shapely @ file:///home/conda/feedstock_root/build_artifacts/shapely_1665624546039/work
> shiboken2==5.13.2
> six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
> sleap==1.3.1
> statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1654787101575/work
> tensorboard==2.7.0
> tensorboard-data-server==0.6.1
> tensorboard-plugin-wit==1.8.0
> tensorflow==2.7.0
> tensorflow-estimator==2.7.0
> tensorflow-hub @ file:///home/conda/feedstock_root/build_artifacts/tensorflow-hub_1678880940235/work/wheel_dir/tensorflow_hub-0.13.0-py2.py3-none-any.whl
> tensorflow-io-gcs-filesystem==0.23.1
> termcolor==1.1.0
> threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
> tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1591280222285/work
> tomli==2.0.0
> toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
> typing_extensions==4.0.1
> tzlocal==5.0.1
> unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1649111917568/work
> urllib3==1.26.7
> Werkzeug==2.0.2
> wrapt==1.13.3
> zipp==3.15.0

Unfortunately, I'm still getting the same error. I'm hesitant to simply delete my working sleap env and reinstall because, well, that's what I did that got me into this mess! I'd been trying to install the new version without using mamba (that was a mistake) all week; downloading mamba got it rolling, but I'm not sure at what cost. When I installed sleap today using mamba, I should note that there was _no_ working sleap env under the listed envs; I'd deleted everything but my base env. 

My workflow for actually executing any training jobs is pretty broken now, so I really hope those results help us untangle what's happening! I can evaluate models, though.

**Comment by eringiglio** [comment] 2023-09-04 20:53
@roomrys ' test installation line worked successfully for me to reinstall, fwiw! 

mamba create -y -n sleap_test_0 -c conda-forge -c nvidia -c sleap -c anaconda sleap=1.3.1=py37_11

**Comment by roomrys** [comment] 2023-09-05 20:28
Hi @eringiglio, @maedat,

Thank you for trying out the proposed solution! I will move the other 1.3.1 packages from our main channel to the dev channel so that only the newer package can be pulled in - avoiding this issue.

Thanks again,
Liezl

**Comment by eringiglio** [comment] 2023-09-05 20:47
Delighted to be of use!

**Comment by roomrys** [comment] 2023-09-05 20:58
Closing this issue as completed, but if anyone else experiences trouble please feel free to comment below and I will reopen!

**Closed by roomrys** 2023-09-05 20:58 UTC
Labels: bug
