### ISSUE TITLE
Encoding Multiple Videos using Batch File

### ISSUE THREAD

**Issue by ARTUR551** [talmolab/sleap#710] opened 2022-04-19 19:29 UTC
Hi,

Thank you for developing SLEAP!

I have been running into the same error over and over.
After the GUI finishes training and tries to start the inference an error occurs:

KeyError: "Unable to load frame 7679 from MediaVideo(filename='D:/SLEAP/TEST_001.mp4', grayscale=False, bgr=True, dataset='', input_format='channels_last')."
    'open_in_gui': False,
    'peak_threshold': 0.2,
    'tracking.tracker': None,
    'tracking.target_instance_count': None,
    'tracking.pre_cull_to_target': None,
    'tracking.pre_cull_iou_threshold': None,
    'tracking.post_connect_single_breaks': None,
    'tracking.clean_instance_count': None,
    'tracking.clean_iou_threshold': None,
Process return code: 1

I already tried with several single videos and pairs of them. I also tried to cut the last frames (even seconds) of several videos and I always get the same error. It is always with the last couple of frames of any video.
It also occurs when I try to run directly the inference process.

Is it a bug or I'm using wrong videos?

Thanks again!

Artur

**Comment by ARTUR551** [comment] 2022-04-20 10:49
Hi roomrys,

Thank you for your timely response.
The reencoding solution worked.

Is there a way to batch (or folder) reencode? (I'm not an expert in programming) I have hundreds of videos to analyze.
Or the reencoding is just needed for the training and inference?

Thanks again,

Artur

**Comment by roomrys** [comment] 2022-04-20 17:57
Hi @ARTUR551,

Great that it worked!

To do any computer vision-based processing (as needed in training and inference), we require the video to be reliably seekable. That being said if you have many videos within a folder that are not reliably seekable and would like to perform training and/or inference on them, then we can create a batch file within the folder that will run the re-encode command on all the files (of a specific extension). Since we are running a command on an entire folder, I recommend having backup of the videos just to be safe. 

To run the re-encode on an entire directory of videos (on Windows - if you are on another system, I can create instructions for a similar process):
1. Navigate to the directory containing all the videos
2. Create a new text file named "script.txt"
3. Inside "script.txt", paste the following command:
```
for %%V in ("*.mp4") do ffmpeg -y -i "%%V" -c:v libx264 -pix_fmt yuv420p -preset superfast -crf 23 "output\%%~nV.mp4"
```

> Note: with the above command, we only search for files ending with the .mp4 extension. If you would like to search for a different extension, change the `*.mp4` to `*.<another extension>`

4. Save "script.txt" and head back to the directory containing all the videos
5. Change the extension of "script.txt" to "script.bat" - this will change the text file to a batch file which we can execute from the command line
6. Create a new directory called "output" - this is where we will store all the re-encoded videos instead of overwriting the originals
7. Open a terminal in the directory containing all the videos
8. Run `script.bat` from within the terminal

Re-encoding does take a bit of time, so we recommend only doing it on the videos you will use for training and inference. Let me know if this works for you.

Thanks,
Liezl

**Comment by roomrys** [comment] 2022-05-05 17:29
We should add documentation on this.

**Comment by talmo** [comment] 2022-05-12 23:11
Closing as a duplicate of the objectives of #581.

**Closed by talmo** 2022-05-12 23:11 UTC
Labels: duplicate, documentation
