### ISSUE TITLE
Cannot merge two project files

### ISSUE THREAD

**Issue by tararaam** [talmolab/sleap#592] opened 2021-10-13 06:38 UTC
I am trying to merge one project file into the other so I can run training on the complete set of labels, but I get this error in the command line:
Labels.skeleton can only be used when there is only a single skeleton saved in the labels. Use Labels.skeletons instead.

I have tried merging in both directions and still get this error either way. The same skeleton was used for both project files so I'm not sure what the issue is. Any tips appreciated. Thanks!

**Comment by talmo** [comment] 2021-10-20 16:50
Closing because we fixed this for now, but definitely reply here if it happens again and we manage to figure out how to reproduce the issue.

For future reference: the problem was that there were multiple skeletons in each SLP file (both base and the new). Some skeletons were topologically different, some were identical. Not clear why they were inserted in the first place (generated in old version, or result of a new bug).

**Closed as completed by talmo** 2021-10-20 16:50 UTC
